# Generated by Django 2.2.5 on 2020-03-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200328_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymoney', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('1', '水费'), ('2', '电费'), ('3', '物业费')], max_length=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.resident')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
                'db_table': 'bill',
            },
        ),
    ]
