# Generated by Django 2.2.5 on 2020-03-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='goodnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.goods'),
        ),
    ]
