# Generated by Django 2.2.5 on 2020-04-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200330_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
