# Generated by Django 2.2.5 on 2020-04-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200401_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavemessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contend', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('res', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.resident')),
                ('wor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.worker')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'leavemessage',
            },
        ),
    ]
