# Generated by Django 2.2.5 on 2020-04-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_leavemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leavemessage',
        ),
    ]
