# Generated by Django 2.2.5 on 2020-04-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_delete_leavemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('ordernum', models.IntegerField(primary_key=True, serialize=False)),
                ('ordertime', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('money', models.IntegerField()),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.resident')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'order',
            },
        ),
    ]
