# Generated by Django 2.2.5 on 2020-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_order_is_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordernum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
