# Generated by Django 2.2.5 on 2020-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20200406_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
