# Generated by Django 2.2.5 on 2020-04-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_shop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
