# Generated by Django 2.2.5 on 2020-04-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_order_tele'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.order'),
        ),
    ]
